import os
import art
import random

def generate_logo(font_text, font="random"):
    try:
        total_terminal_columns = list(os.get_terminal_size())[0]
        logo = art.text2art(font_text, font=font)
        return logo if total_terminal_columns >= len(str(logo).split("\n")[0]) else  generate_logo(font_text, font)
    except Exception as e:
        print(" error generated by the art library : ", e)

def get_random_color(COLORS):
    color_name = random.choice(list(COLORS.keys()))
    return COLORS.get(color_name) if color_name != "reset" else get_random_color(COLORS)
